# Generated by Django 4.2.16 on 2026-08-14 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_rich_travel_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='Day 1, Day 2, etc.')),
                ('title', models.CharField(help_text="Short headline for the day, e.g. 'Arrival in Goa & beach relaxation'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='What actually happens this day: sights, transfers, meals, free time. This is specific to this package.')),
                ('activities', models.TextField(blank=True, help_text='One activity/stop per line for this day, e.g. "Old Goa heritage walk" (optional).')),
                ('meals', models.CharField(blank=True, choices=[('', 'Not specified'), ('B', 'Breakfast'), ('BL', 'Breakfast & Lunch'), ('BD', 'Breakfast & Dinner'), ('BLD', 'Breakfast, Lunch & Dinner'), ('none', 'No meals included')], default='', max_length=10)),
                ('overnight_stay', models.CharField(blank=True, help_text='Optional: city/hotel where the traveler stays overnight, e.g. "Overnight in Baga, Goa"', max_length=150)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='destinations.travelpackage')),
            ],
            options={
                'ordering': ['package', 'day_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='itineraryday',
            constraint=models.UniqueConstraint(fields=('package', 'day_number'), name='unique_package_day_number'),
        ),
    ]
